### ISSUE TITLE
Generate signing certificate fingerprint for Oauth 2 login

### ISSUE THREAD

**Issue by FarsanRashid** [KhelaHobe/AndroidApp#2]
Generate certificate fingerprint for your package. 
![Follow the steps to generate certificate fingerprint](https://user-images.githubusercontent.com/8214491/54009864-b4755900-4196-11e9-8560-e162958c462f.png)

**Comment by mahadi18** [comment]
**SHA1:** E6:E0:21:AB:2A:74:31:6A:56:E0:F1:7A:29:4E:BD:28:8E:BF:01:3A

_Package Name: _ com.khelahobe.androidapp
